<a href="https://colab.research.google.com/github/afonsodebritto/IC-GeologiQA/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

### Libraries

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors




### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.1702, 0.5670, 0.5310, 0.9066],
        [0.4731, 0.7489, 0.2989, 0.7129],
        [0.3063, 0.8307, 0.6160, 0.0966]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones tensors
It can be used to create masks for tensors

In [ ]:
# Create a tensor full of zeros
zeros = torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Default data type of a tensor in PyTorch
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)

In [ ]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step_tensor = torch.arange(start=1, end=1000, step=77)

In [ ]:
step_tensor

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & DeepLearning
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [ ]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # Datatype of the tensor
                               device=None,         # A tensor can live on the CPU or the GPU
                               requires_grad=False) # Track gradients with the operations

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# torch.half == torch.float16
float_16_tensor = float_32_tensor.type(torch.half)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not right device - to get device from a tensor, use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)

In [ ]:
# Checking the attributes of a tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3510, 0.3390, 0.5868, 0.5473],
        [0.6290, 0.2374, 0.7161, 0.5958],
        [0.4504, 0.2593, 0.7476, 0.9541]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10 of the tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules of matrix multiplication:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [ ]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### Of of the common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8, 11],
                         [9,12]])

In [ ]:
# torch.matmul(tensor_A, tensor_B)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our shape issues, we can just **transpose** one of the matrixes.
A **transpose** will switch the axes of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean & sum (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
# x.min() also works
torch.min(x)

tensor(0)

In [ ]:
# Find the max
# x.max() also works
torch.max(x)

tensor(90)

In [ ]:
# Find the mean
# torch.mean requires dtype = float
# x.type(torch.float32).mean() also works
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# Find the sum
# x.sum() also works
torch.sum(x)

tensor(450)

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index positions of target tensor where the min value occurs
x.argmin()

tensor(0)

In [ ]:
# # Find the position in tensor that has the maximum value with argmax() -> returns index positions of target tensor where the max value occurs
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other on a specific dimension
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions (swapped) in a certain way

In [ ]:
# Create a tensor
x = torch.arange(1, 10)

In [ ]:
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)

In [ ]:
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (a view of a tensor shares the same memory as the original input)
z[:,0] = 5

In [ ]:
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)

In [ ]:
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previou shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previou shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to a rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)

In [ ]:
x_permuted.size

<function Tensor.size>

In [ ]:
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all the values of 0th and 1st dimension, but only index 1 on 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all the values from the 0th dimension, but only the index 1 value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and first dimension and all values from second dimension
x[0, 0, :]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

PyTorch has functionality to interact with NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
# When converting numpy -> torch, pytorch will infer the dtype from the nparray
# .type(torch.float32)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will happen to the tensor?
array = array + 1
# The tensor and array do not share memory
# The tensor does not change
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# The data type of the np array reflects the data type of the tensor
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to the array?
tensor = tensor + 1
# The tensor and array do not share memory
# The array does not change
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([3., 3., 3., 3., 3., 3., 3.]))

### Reproducibility (trying to rake random out random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again... `

To reduce the randomness in neural newtorks and PyTorch comes the concept of a **random seed**.

Essentially, what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9677, 0.4687, 0.8567, 0.4353],
        [0.7690, 0.8810, 0.9198, 0.6688],
        [0.0544, 0.3965, 0.9363, 0.2106]])
tensor([[0.2452, 0.6255, 0.1201, 0.6889],
        [0.7960, 0.7111, 0.0923, 0.9527],
        [0.9183, 0.0804, 0.5157, 0.0713]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs

In [ ]:
# Check for GPU acess with PyTorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1