<a href="https://colab.research.google.com/github/afonsodebritto/IC-GeologiQA/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors




### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Get tensor back as Python int
scalar.item()

7

In [4]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [6]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [7]:
TENSOR.ndim

3

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data.

In [9]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [10]:
random_tensor

tensor([[0.9170, 0.8291, 0.2921, 0.1989],
        [0.8127, 0.0129, 0.9268, 0.2836],
        [0.4596, 0.2354, 0.6621, 0.0111]])

In [11]:
random_tensor.ndim

2

In [12]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels

In [13]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones tensors
It can be used to create masks for tensors

In [14]:
# Create a tensor full of zeros
zeros = torch.zeros(size=(3,4))

In [15]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
random_tensor * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(size=(3,4))

In [18]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# Default data type of a tensor in PyTorch
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [20]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)

In [21]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
step_tensor = torch.arange(start=1, end=1000, step=77)

In [23]:
step_tensor

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [24]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)

In [25]:
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & DeepLearning
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [29]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # Datatype of the tensor
                               device=None,         # A tensor can live on the CPU or the GPU
                               requires_grad=False) # Track gradients with the operations

In [30]:
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
# torch.half == torch.float16
float_16_tensor = float_32_tensor.type(torch.half)

In [33]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor.dtype

torch.float16

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)

In [37]:
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])